environments:
  - name: dev
    configs:
      endpoints:
          production:
              url: 'https://localhost:9443/am/sample/pizzashack/v1'
      deploymentEnvironments:
          - displayOnDevportal: true
            deploymentEnvironment: Default
            deploymentVhost : localhost
