environments:
  - name: dev
    configs:
      endpoints:
          production:
              url: 'https://jsonplaceholder.typicode.com/'
      deploymentEnvironments:
          - displayOnDevportal: true
            deploymentEnvironment: Default
            deploymentVhost : localhost
